FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:20-bookworm 

# Clone testing projects
RUN mkdir /test-projects/
RUN git clone https://github.com/chienvh/ASP.Net-MVC-Entity-Framework-by-Example-Project.git /test-projects/ASP.Net-MVC-Entity-Framework-by-Example-Project \
  && chown node:node -R /test-projects

  
  

